<?php

namespace AppBundle\Repository;

/**
 * EntaineurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntaineurRepository extends \Doctrine\ORM\EntityRepository
{
}
