<?php

namespace AppBundle\Repository;

/**
 * HistoriqueAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueAbonnementRepository extends \Doctrine\ORM\EntityRepository
{
}
