<?php

namespace AppBundle\Repository;

/**
 * HistoriqueExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueExerciceRepository extends \Doctrine\ORM\EntityRepository
{
}
