<?php

namespace AppBundle\Entity\Repository;

/**
 * ExercicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExercicesRepository extends \Doctrine\ORM\EntityRepository
{
}
