<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBhs1vqz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBhs1vqz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBhs1vqz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBhs1vqz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBhs1vqz\appProdProjectContainer(array(
    'container.build_hash' => 'Bhs1vqz',
    'container.build_id' => '2b2d9d1a',
    'container.build_time' => 1531094876,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBhs1vqz');
