<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'abonnement.get.all' shared service.

include_once $this->targetDirs[3].'/src/AppBundle/Services/AbonnementService.php';

return $this->services['abonnement.get.all'] = new \AppBundle\Services\AbonnementService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
