<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBus4mtn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBus4mtn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBus4mtn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBus4mtn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBus4mtn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bus4mtn',
    'container.build_id' => 'a5486d9b',
    'container.build_time' => 1531304141,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBus4mtn');
