<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI6wvxnd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI6wvxnd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI6wvxnd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI6wvxnd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerI6wvxnd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'I6wvxnd',
    'container.build_id' => 'c723cbcd',
    'container.build_time' => 1530564446,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerI6wvxnd');
